const workerMessageTypes = {
  CONNECTION_ID: 'CONNECTION_ID',
  NEW_RENDER: 'NEW_RENDER',
  SOURCE: 'SOURCE',
  API_DATA: 'API_DATA',
  ASSET_ID: 'ASSET_ID',
  GET_DATASETS: 'GET_DATASETS',
  GET_TABLE_NAMES: 'GET_TABLE_NAMES',
  GET_DATASET_COLUMNNAMES: 'GET_DATASET_COLUMNNAMES',
  GET_TABLE_COLUMNNAMES: 'GET_TABLE_COLUMNNAMES',
};

export default workerMessageTypes;
