//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.14 at 07:59:11 PM IST 
//


package com.graphiti.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="query" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="connectionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="typeOfChart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isPagination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xaxisVencoding" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="metrics" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="yaxisVencoding" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="metrics" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="colorEncoding" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="metrics" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="detailEncoding" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "query",
    "from",
    "to",
    "connectionId",
    "typeOfChart",
    "isPagination",
    "xaxisVencoding",
    "yaxisVencoding",
    "colorEncoding",
    "detailEncoding"
})
@XmlRootElement(name = "ChartConfigurations")
public class ChartConfigurations {

    protected String query;
    protected Integer from;
    protected Integer to;
    protected String connectionId;
    protected String typeOfChart;
    protected String isPagination;
    protected ChartConfigurations.XaxisVencoding xaxisVencoding;
    protected ChartConfigurations.YaxisVencoding yaxisVencoding;
    protected ChartConfigurations.ColorEncoding colorEncoding;
    protected ChartConfigurations.DetailEncoding detailEncoding;

    /**
     * Gets the value of the query property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuery(String value) {
        this.query = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFrom(Integer value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTo(Integer value) {
        this.to = value;
    }

    /**
     * Gets the value of the connectionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionId() {
        return connectionId;
    }

    /**
     * Sets the value of the connectionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionId(String value) {
        this.connectionId = value;
    }

    /**
     * Gets the value of the typeOfChart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfChart() {
        return typeOfChart;
    }

    /**
     * Sets the value of the typeOfChart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfChart(String value) {
        this.typeOfChart = value;
    }

    /**
     * Gets the value of the isPagination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPagination() {
        return isPagination;
    }

    /**
     * Sets the value of the isPagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPagination(String value) {
        this.isPagination = value;
    }

    /**
     * Gets the value of the xaxisVencoding property.
     * 
     * @return
     *     possible object is
     *     {@link ChartConfigurations.XaxisVencoding }
     *     
     */
    public ChartConfigurations.XaxisVencoding getXaxisVencoding() {
        return xaxisVencoding;
    }

    /**
     * Sets the value of the xaxisVencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartConfigurations.XaxisVencoding }
     *     
     */
    public void setXaxisVencoding(ChartConfigurations.XaxisVencoding value) {
        this.xaxisVencoding = value;
    }

    /**
     * Gets the value of the yaxisVencoding property.
     * 
     * @return
     *     possible object is
     *     {@link ChartConfigurations.YaxisVencoding }
     *     
     */
    public ChartConfigurations.YaxisVencoding getYaxisVencoding() {
        return yaxisVencoding;
    }

    /**
     * Sets the value of the yaxisVencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartConfigurations.YaxisVencoding }
     *     
     */
    public void setYaxisVencoding(ChartConfigurations.YaxisVencoding value) {
        this.yaxisVencoding = value;
    }

    /**
     * Gets the value of the colorEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link ChartConfigurations.ColorEncoding }
     *     
     */
    public ChartConfigurations.ColorEncoding getColorEncoding() {
        return colorEncoding;
    }

    /**
     * Sets the value of the colorEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartConfigurations.ColorEncoding }
     *     
     */
    public void setColorEncoding(ChartConfigurations.ColorEncoding value) {
        this.colorEncoding = value;
    }

    /**
     * Gets the value of the detailEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link ChartConfigurations.DetailEncoding }
     *     
     */
    public ChartConfigurations.DetailEncoding getDetailEncoding() {
        return detailEncoding;
    }

    /**
     * Sets the value of the detailEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartConfigurations.DetailEncoding }
     *     
     */
    public void setDetailEncoding(ChartConfigurations.DetailEncoding value) {
        this.detailEncoding = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="metrics" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dimensions",
        "metrics"
    })
    public static class ColorEncoding {

        protected List<String> dimensions;
        protected List<String> metrics;

        /**
         * Gets the value of the dimensions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dimensions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDimensions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDimensions() {
            if (dimensions == null) {
                dimensions = new ArrayList<String>();
            }
            return this.dimensions;
        }

        /**
         * Gets the value of the metrics property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the metrics property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMetrics().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getMetrics() {
            if (metrics == null) {
                metrics = new ArrayList<String>();
            }
            return this.metrics;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dimensions"
    })
    public static class DetailEncoding {

        protected List<String> dimensions;

        /**
         * Gets the value of the dimensions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dimensions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDimensions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDimensions() {
            if (dimensions == null) {
                dimensions = new ArrayList<String>();
            }
            return this.dimensions;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="metrics" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dimensions",
        "metrics"
    })
    public static class XaxisVencoding {

        protected List<String> dimensions;
        protected List<String> metrics;

        /**
         * Gets the value of the dimensions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dimensions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDimensions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDimensions() {
            if (dimensions == null) {
                dimensions = new ArrayList<String>();
            }
            return this.dimensions;
        }

        /**
         * Gets the value of the metrics property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the metrics property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMetrics().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getMetrics() {
            if (metrics == null) {
                metrics = new ArrayList<String>();
            }
            return this.metrics;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dimensions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="metrics" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dimensions",
        "metrics"
    })
    public static class YaxisVencoding {

        protected List<String> dimensions;
        protected List<String> metrics;

        /**
         * Gets the value of the dimensions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dimensions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDimensions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDimensions() {
            if (dimensions == null) {
                dimensions = new ArrayList<String>();
            }
            return this.dimensions;
        }

        /**
         * Gets the value of the metrics property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the metrics property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMetrics().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getMetrics() {
            if (metrics == null) {
                metrics = new ArrayList<String>();
            }
            return this.metrics;
        }

    }

}
